if (NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    return()
endif ()

option(AQUILA_AUTO_INSTALL "Install missing system packages with the distribution's package manager (uses sudo)" OFF)
if (DEFINED ENV{AQUILA_AUTO_INSTALL})
    set(AQUILA_AUTO_INSTALL ON)
endif ()

find_program(_aquila_apt apt-get)
find_program(_aquila_pacman pacman)
find_program(_aquila_dnf dnf)
find_program(_aquila_zypper zypper)

set(_aquila_missing_labels "")
set(_aquila_missing_apt "")
set(_aquila_missing_pacman "")
set(_aquila_missing_dnf "")
set(_aquila_missing_zypper "")

macro(_aquila_require found label apt pacman dnf zypper)
    if (NOT ${found})
        list(APPEND _aquila_missing_labels "${label}")
        list(APPEND _aquila_missing_apt ${apt})
        list(APPEND _aquila_missing_pacman ${pacman})
        list(APPEND _aquila_missing_dnf ${dnf})
        list(APPEND _aquila_missing_zypper ${zypper})
    endif ()
endmacro()

find_package(X11 QUIET)
_aquila_require(X11_FOUND "X11 headers" libx11-dev libx11 libX11-devel libX11-devel)
_aquila_require(X11_Xrandr_FOUND "XRandR headers" libxrandr-dev libxrandr libXrandr-devel libXrandr-devel)
_aquila_require(X11_Xinerama_FOUND "Xinerama headers" libxinerama-dev libxinerama libXinerama-devel libXinerama-devel)
_aquila_require(X11_Xcursor_FOUND "Xcursor headers" libxcursor-dev libxcursor libXcursor-devel libXcursor-devel)
_aquila_require(X11_Xi_FOUND "XInput headers" libxi-dev libxi libXi-devel libXi-devel)
_aquila_require(X11_Xkb_FOUND "XKB headers" libx11-dev libx11 libX11-devel libX11-devel)

if (AQUILA_BUILD_VULKAN_LOADER)
    _aquila_require(X11_xcb_FOUND "XCB headers (Vulkan loader)" libxcb1-dev libxcb libxcb-devel libxcb-devel)
endif ()

if (NOT _aquila_missing_labels)
    return()
endif ()

if (_aquila_apt)
    list(REMOVE_DUPLICATES _aquila_missing_apt)
    list(JOIN _aquila_missing_apt " " _packages)
    set(_aquila_install_command "sudo apt-get install -y ${_packages}")
elseif (_aquila_pacman)
    list(REMOVE_DUPLICATES _aquila_missing_pacman)
    list(JOIN _aquila_missing_pacman " " _packages)
    set(_aquila_install_command "sudo pacman -S --needed --noconfirm ${_packages}")
elseif (_aquila_dnf)
    list(REMOVE_DUPLICATES _aquila_missing_dnf)
    list(JOIN _aquila_missing_dnf " " _packages)
    set(_aquila_install_command "sudo dnf install -y ${_packages}")
elseif (_aquila_zypper)
    list(REMOVE_DUPLICATES _aquila_missing_zypper)
    list(JOIN _aquila_missing_zypper " " _packages)
    set(_aquila_install_command "sudo zypper install -y ${_packages}")
else ()
    set(_aquila_install_command "")
endif ()

list(JOIN _aquila_missing_labels ", " _missing_text)

if (AQUILA_AUTO_INSTALL AND _aquila_install_command)
    message(STATUS "Aquila: installing missing system packages: ${_aquila_install_command}")
    execute_process(COMMAND bash -c "${_aquila_install_command}" RESULT_VARIABLE _aquila_install_result)
    if (NOT _aquila_install_result EQUAL 0)
        message(FATAL_ERROR "Aquila: package installation failed. Run it yourself: ${_aquila_install_command}")
    endif ()
    message(FATAL_ERROR "Aquila: system packages installed. Configure again to pick them up.")
endif ()

if (_aquila_install_command)
    message(FATAL_ERROR "Aquila is missing system packages: ${_missing_text}\n"
                        "Install them with:\n  ${_aquila_install_command}\n"
                        "or configure with -DAQUILA_AUTO_INSTALL=ON to let CMake run that command.")
endif ()
message(FATAL_ERROR "Aquila is missing system packages: ${_missing_text}. Install the development packages for them with your package manager.")
