set(AQUILA_SLANG_VERSION 2026.13.1)
option(AQUILA_FETCH_SLANG "Always use the pinned Slang release instead of the one in a Vulkan SDK" OFF)
set(AQUILA_DEPS_DIR "${CMAKE_SOURCE_DIR}/.deps" CACHE PATH "Where Aquila keeps downloaded prebuilt dependencies")

function(_aquila_slang_package out_name)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
        set(_arch aarch64)
    else ()
        set(_arch x86_64)
    endif ()

    if (WIN32)
        set(_platform "windows-${_arch}")
        set(_extension zip)
    elseif (APPLE)
        set(_platform "macos-${_arch}")
        set(_extension zip)
    else ()
        set(_platform "linux-${_arch}-glibc-2.28")
        set(_extension tar.gz)
    endif ()

    set(${out_name} "slang-${AQUILA_SLANG_VERSION}-${_platform}.${_extension}" PARENT_SCOPE)
endfunction()

function(_aquila_fetch_slang out_root)
    _aquila_slang_package(_archive)
    string(REGEX REPLACE "\\.(zip|tar\\.gz)$" "" _folder "${_archive}")
    set(_root "${AQUILA_DEPS_DIR}/${_folder}")

    if (NOT EXISTS "${_root}/include/slang.h")
        set(_download "${AQUILA_DEPS_DIR}/${_archive}")
        set(_url "https://github.com/shader-slang/slang/releases/download/v${AQUILA_SLANG_VERSION}/${_archive}")
        message(STATUS "Aquila: downloading Slang ${AQUILA_SLANG_VERSION} (${_archive})")
        file(MAKE_DIRECTORY "${AQUILA_DEPS_DIR}")
        file(DOWNLOAD "${_url}" "${_download}" STATUS _status SHOW_PROGRESS)
        list(GET _status 0 _code)
        if (NOT _code EQUAL 0)
            list(GET _status 1 _reason)
            file(REMOVE "${_download}")
            message(FATAL_ERROR "Aquila: could not download Slang from ${_url}: ${_reason}")
        endif ()
        file(REMOVE_RECURSE "${_root}")
        file(ARCHIVE_EXTRACT INPUT "${_download}" DESTINATION "${_root}")
        file(REMOVE "${_download}")
    endif ()

    set(${out_root} "${_root}" PARENT_SCOPE)
endfunction()

function(aquila_provide_slang)
    set(_root "")
    set(_include "")
    if (NOT AQUILA_FETCH_SLANG AND VULKAN_SDK AND EXISTS "${VULKAN_SDK}/include/slang/slang.h")
        set(_root "${VULKAN_SDK}")
        set(_include "${VULKAN_SDK}/include")
        message(STATUS "Aquila: using Slang from the Vulkan SDK at ${VULKAN_SDK}")
    else ()
        _aquila_fetch_slang(_root)
        set(_include "${_root}/aquila-include")
        file(GLOB _headers "${_root}/include/*.h")
        file(COPY ${_headers} DESTINATION "${_include}/slang")
        message(STATUS "Aquila: using Slang ${AQUILA_SLANG_VERSION} from ${_root}")
    endif ()

    find_library(AQUILA_SLANG_LIBRARY
        NAMES slang slang-compiler
        PATHS "${_root}/lib"
        NO_DEFAULT_PATH NO_CACHE REQUIRED
    )

    add_library(Slang::Slang SHARED IMPORTED GLOBAL)
    set_target_properties(Slang::Slang PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_include}")
    if (WIN32)
        file(GLOB _all_runtime "${_root}/Bin/slang*.dll" "${_root}/bin/slang*.dll")
        list(REMOVE_DUPLICATES _all_runtime)
        set(_runtime "${_all_runtime}")
        list(FILTER _runtime INCLUDE REGEX "/slang\\.dll$")
        if (NOT _runtime)
            message(FATAL_ERROR "Aquila: slang.dll was not found under ${_root}")
        endif ()
        list(GET _runtime 0 _runtime)
        set_target_properties(Slang::Slang PROPERTIES
            IMPORTED_IMPLIB "${AQUILA_SLANG_LIBRARY}"
            IMPORTED_LOCATION "${_runtime}"
        )
        set(AQUILA_SLANG_RUNTIME_FILES "${_all_runtime}" CACHE INTERNAL "")
    else ()
        set_target_properties(Slang::Slang PROPERTIES IMPORTED_LOCATION "${AQUILA_SLANG_LIBRARY}")
        set(AQUILA_SLANG_RUNTIME_FILES "" CACHE INTERNAL "")
    endif ()
endfunction()
