if (CMAKE_C_COMPILER OR CMAKE_CXX_COMPILER)
    return()
endif ()

if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    find_program(_aquila_clang_cl clang-cl)
    if (_aquila_clang_cl)
        set(CMAKE_C_COMPILER clang-cl CACHE STRING "C compiler")
        set(CMAKE_CXX_COMPILER clang-cl CACHE STRING "C++ compiler")
    endif ()
else ()
    find_program(_aquila_clang clang)
    find_program(_aquila_clangxx clang++)
    if (_aquila_clang AND _aquila_clangxx)
        set(CMAKE_C_COMPILER clang CACHE STRING "C compiler")
        set(CMAKE_CXX_COMPILER clang++ CACHE STRING "C++ compiler")
    else ()
        message(WARNING "Aquila: clang was not found, falling back to the system compiler. Install clang for the supported toolchain.")
    endif ()
endif ()
